# Generated by Django 3.1 on 2020-10-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_conceptdb_vocabdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptdb',
            name='cdb_file',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vocabdb',
            name='vocab_file',
            field=models.CharField(max_length=500),
        ),
    ]
