# Generated by Django 3.1 on 2020-10-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20201021_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptdb',
            name='cdb_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='vocabdb',
            name='vocab_file',
            field=models.FileField(upload_to=''),
        ),
    ]
