# Generated by Django 3.1 on 2020-10-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20201021_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptdb',
            name='cdb_file',
            field=models.FileField(upload_to='data_models'),
        ),
        migrations.AlterField(
            model_name='vocabdb',
            name='vocab_file',
            field=models.FileField(upload_to='data_models'),
        ),
    ]
